version: '3.9'

services:

  php:
    container_name: s_php
    build:
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
    volumes:
      - $MAIN_PATH:/var/www
    env_file:
      - .env
    networks:
      - main

  mysql:
    container_name: s_mysql
    image: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - $MYSQL_PATH:/var/lib/mysql
    env_file:
      - .env
    networks:
      - main

  nginx:
    container_name: s_nginx
    image: nginx:1.20.1-alpine
    depends_on:
      - php
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - $MAIN_PATH:/var/www
      - $MAIN_PATH/docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main

networks:
  main:
    driver: bridge